### ISSUE TITLE
json2dot crashes on routing Harris

### ISSUE THREAD

**Issue by dillonhuff** [StanfordAHA/CGRAGenerator#89] opened 2018-06-15 01:41 UTC
@steveri I'm trying to push Harris through the entire flow.
I'm using the dev branches of coreir and CGRAMapper, and my own branch of the CGRA that I took off of dev.

When I map Harris and try to run it through json2dot I get an error that looks like it is related to the bit routing network. The error is an assertion failure on line 55 of json2dot.py:

```python
assert rval.find('bitPE.in') >= 0
```

The original harris json is [here](https://github.com/StanfordAHA/CGRAGenerator/blob/mac_bitstream_testing/tests/yosys_proc_check/design_top_golden_original_mapped.json)

**Comment by steveri** [comment] 2018-06-16 15:56
I think this is fixed (in dev branch), try it now.
I have not checked yet to see if the resulting dot file can be routed by serpent...

**Comment by dillonhuff** [comment] 2018-06-20 20:32
Thanks Steve.

Harris now gets through json2dot, but serpent is now crashing.
The error is on line 690 of cgra_info.py in find_regbit.

```bash
ERROR: Cannot find <reg> tag in sb; did you forget to setenv CGRA_ALL_REG 1?
```

Do you know what this error means?

**Comment by steveri** [comment] 2018-06-21 16:42
It thinks there's something wrong with the cgra_info.txt file in CGRAGenerator/hardware/generator_z/top
In particular, every tag <sb> should have one or more sub-tags <reg> e.g. see below.

To verify that each sb has at least one register:
```
% egrep '<sb|<reg' cgra_info.txt | sed 's/reg.*/reg/' | uniq | less
    <sb feature_address='9' bus='BUS1'>
        <reg
    <sb feature_address='8' bus='BUS16'>
        <reg
    <sb feature_address='9' bus='BUS1'>
        <reg
    <sb feature_address='8' bus='BUS16'>
        <reg
    <sb feature_address='9' bus='BUS1'>
        <reg
```

Also note, when you run serpent with the -v option, you should see the following in the output, verifying that it's using the right cgra_info.txt:
```
######################################################
# serpent.py: Read cgra info
Using config file '/nobackup/steveri/github/CGRAGenerator/hardware/generator_z/top/cgra_info.txt'
```

You could try and regenerate the CGRA and see if you still get the error
`% cd CGRAGenerator/hardware/generator_z/top; ./build_cgra.sh`

And/or if you can send me your latest harris.dot and point me toward the relevant cgra_info.txt I can try and reproduce the error on my end (I get a whole different error when I run serpent on the harris.dot I have now...)

**Comment by dillonhuff** [comment] 2018-06-26 23:46
@stevenbell thanks for those suggestions. I re-generated the CGRA and am now getting a different error. It looks like serpent is now getting stuck in a loop while trying to place the 3rd tile.

Is this the error that you get? The problem I see looks like:

```bash
NO path not available
/horowitz/users/dhuff/CGRAGenerator/bitstream/bsbuilder/serpent.py/1489: Tile 164 no good; undo and try again:
# No route to 'lb_padded_2_stencil_update_stream$lbmem_1_0'
```

**Comment by dillonhuff** [comment] 2018-06-26 23:46
Sorry @stevenbell didn't mean to reference you. I meant @steveri

**Comment by steveri** [comment] 2018-06-27 00:40
@dillonhuff this is the error i get when i run in branch dev (below).   I have a version in branch 'harris' that gets a little farther, but still not very close to finishing successfully yet...

```
% cd CGRAGenerator/bitstream/bsbuilder/serpent.py -v harris.dot
...
ERROR What is 'lb_padded_2_stencil_update_stream$lb1d_0$reg_1'?
Traceback (most recent call last):
  File "../../serpent.py", line 3262, in <module>
    main()
  File "../../serpent.py", line 377, in main
    process_nodes('INPUT')
  File "../../serpent.py", line 1854, in process_nodes
    assert False, "ERROR What is '%s'?" % dname
AssertionError: ERROR What is 'lb_padded_2_stencil_update_stream$lb1d_0$reg_1'?
```

**Comment by steveri** [comment] 2018-06-27 00:41
PS The  harris dot file I use can be found here, on kiwi:

`/nobackup/steveri/github/CGRAGenerator/bitstream/bsbuilder/testdir/harris/harris.dot`

**Comment by dillonhuff** [comment] 2018-06-27 02:20
I just tried that file using the harris branch. I can get a placement out to tile 25. Then I get this error:

```bash
  File "../../bitstream/bsbuilder/serpent.py", line 2191, in try_again
    try_again_OUTPUT(sname, dname, dtileno, DBG)
  File "../../bitstream/bsbuilder/serpent.py", line 2162, in try_again_OUTPUT
    assert False
AssertionError
```

Does that look familiar to you?

Also will you be around this week? I'd be happy to help out fixing / adding functionality to serpent to get this working, but I don't understand the code very well.

**Comment by steveri** [comment] 2018-06-27 15:17
@dillonhuff  Yes, that err msg looks very familiar, you are now up to speed with the current state of the serpent.
And yes!  I will welcome all the help I can get.  I am here today (Wed.) until at least early afternoon and will probably be here all morning on Friday as well. - SR

**Comment by dillonhuff** [comment] 2018-06-27 17:47
Great. I’ll be at the office by 11:20. We should talk then

**Comment by steveri** [comment] 2018-06-29 16:42
Update: I think we got past the route-to-OUTPUT-on-track-0 node problem, by adding an intermediate add0 no-op node that can be reached on any of the four tracks.  The it went on for maybe another node or two, and now it looks like we'll need to do the same trick and/or a variation when routing to/from a placed register.  E.g. the placed register is attached to a specific track so PNR choices are limited until/unless we add a routable intermediate node.

So now I'm bogged down refactoring serpent so that the code for the OUTPUT fix can be reused more easily for this (and future) similar routing problems...

As a reminder, everything is happening in serpent branch "harris".

**Comment by dillonhuff** [comment] 2018-06-29 18:54
Thats good to hear. Do you have any idea how long this refactoring will take?

**Comment by steveri** [comment] 2018-07-05 17:02
Good news, it looks like I got through all the nodes.  Still cleaning up a bunch of errors though, who knows I might have missed some...in the end there were only about 96 tiles placed.  Realistically speaking, though, I expect it will take another week or two until it routes bug free...note I will be gone on vacation for a week or so starting July 10.

**Comment by dillonhuff** [comment] 2018-07-05 19:18
Thats great news!

Why were only 96 tiles placed? Are there only 96 tiles in the application or is that a bug that needs to be fixed?

**Comment by steveri** [comment] 2018-07-06 17:41
Latest version in harris branch runs to completion w/o error all 96 nodes.  Woohoo!  You should be able to duplicate using the 'harris.dot' that I checked in to the examples subdirectory e.g. I think this will work

```
% cd CGRAGenerator/bitstream/bsbuilder/testdir
% ../serpent.py -v examples/harris.dot > tmp.log
```
Note this will result in multiple tens of thousands of lines of output in tmp.log :octocat: 

Also note that just because it can now produce a bsb file does not mean that the bsb will compile or run!  That will be the next thing to try.

**Comment by dillonhuff** [comment] 2018-07-06 19:50
I just ran serpent to completion on harris.

When I run the bitstream builder to on it I get a crash:

```bash
dhuff@kiwi:~/CGRAGenerator/bitstream/bsbuilder/testdir$ ../bsbuilder.py harris.bsb 
Traceback (most recent call last):
  File "../bsbuilder.py", line 1297, in <module>
    main()
  File "../bsbuilder.py", line 214, in main
    assert False, err_msg
AssertionError: 

# T54_ash(wire,const7__763)  # ashr_760_763_764$binop
I don't know what this is: 'ash(wire,const7__763)'
```

Looks like the builder does not recognize arithmetic shift right maybe?

**Comment by steveri** [comment] 2018-07-09 15:14
Progress is made. Latest issue from bsbuilder:
`AssertionError: ERROR Uh oh looks like more than one guy wants to write 'T21_op2'`

In an attempt at better discipline, I filed a new issue https://github.com/StanfordAHA/CGRAGenerator/issues/91

**Comment by steveri** [comment] 2019-02-06 17:59
Discussion was transferred to issue https://github.com/StanfordAHA/CGRAGenerator/issues/91, which eventually got resolved and closed, see issue https://github.com/StanfordAHA/CGRAGenerator/issues/91 for details...

**Closed by steveri** 2019-02-06 17:59 UTC
