### ISSUE TITLE
LUT unit test occasionally fails with random_op

### ISSUE THREAD

**Issue by leonardt** [StanfordAHA/CGRAGenerator#69] opened 2018-04-11 17:19 UTC
Not exactly sure what's going on here, will need to investigate further

To reproduce
```diff
diff --git a/tests/test_pe/test_pe.py b/tests/test_pe/test_pe.py
index 5c84038..b93f634 100644
--- a/tests/test_pe/test_pe.py
+++ b/tests/test_pe/test_pe.py
@@ -283,8 +283,8 @@ def test_input_modes(signed, worker_id, input_modes):
 def test_lut(strategy, signed, lut_code, worker_id): #, random_op):
     # op = random_op
-    # op = choice(ops)
-    op = "add"
+    op = choice(ops)
+    # op = "add"
     flag_sel = 0xE  # Lut output
     bit2_mode = 0x2  # BYPASS
     bit1_mode = 0x2  # BYPASS
```

**Comment by steveri** [comment] 2018-05-23 17:55
@leonardt Was this ever fixed?  I could not reproduce...I get syntax errors when I do this (on kiwi):

```
% /nobackup/steveri/github/CGRAGenerator/tests/test_pe
% pytest
```

E.g.
```
=======================  test_compute_unit.py  =======================
unhandled exception occurred while testing test_compute_unit
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/logilab/common/pytest.py", line 447, in testfile
    options=self.options, outstream=sys.stderr)
  File "/usr/lib/python2.7/dist-packages/logilab/common/pytest.py", line 763, in __init__
    testLoader=NonStrictTestLoader())
  File "/usr/lib/python2.7/unittest/main.py", line 77, in __init__
    self.module = __import__(module)
  File "test_compute_unit.py", line 19
    ncsim.compile(f'test_{op}_{strategy.__name__}', opcode, tests)
```

**Comment by leonardt** [comment] 2018-05-23 18:52
I have yet to resolve this issue. The error you're seeing is because you're running pytest with python 2.7. The python PE unit tests require python 3.6+

**Comment by steveri** [comment] 2018-05-23 20:31
Hm I thought I had compensated for the 2.7/3.6 discrepancy, but I will recheck and try again...

**Comment by steveri** [comment] 2018-05-30 16:34
I keep running into dumb little problems that I'm thinking you could solve quickly if you were here.  Will you be around toady (Wed) and would you have time to help?  If not, we can find another time...

```
% python3.6 /usr/bin/pytest | & less
DeprecationWarning: the imp module is deprecated in favour of importlib
DeprecationWarning: inspect.getargspec() is deprecated
DeprecationWarning: [logilab-common 1.3] logilab-pytest is deprecated, use another test runner
  run()
============================  test_pe.py  ============================
unhandled exception occurred while testing test_pe
    import pe
ModuleNotFoundError: No module named 'pe'
==========================  testvectors.py  ==========================

=======================  test_compute_unit.py  =======================
    import pytest
ModuleNotFoundError: No module named 'pytest'
no test dir found testing here: /nobackup/steveri/github/CGRAGenerator/tests/test_pe
*******************************************************************************
Ran 2 test cases in 0.02s (0.00s CPU), 2 errors
1 modules OK (2 failed)

```

**Comment by steveri** [comment] 2018-05-30 16:38
@leonardt NVM looks like I made it to Level Two.  I have not yet managed to reproduce anything yet, but I think I'm getting closer anyway ... :)

```
python3.6 /usr/bin/pytest | & less
DeprecationWarning: the imp module is deprecated
DeprecationWarning: inspect.getargspec() is deprecated
DeprecationWarning: [logilab-common 1.3] logilab-pytest is deprecated, use another test runner

=======================  test_compute_unit.py  =======================

============================  test_pe.py  ============================

==========================  testvectors.py  ==========================

no test dir found testing here: /nobackup/steveri/github/CGRAGenerator/tests/test_pe
*******************************************************************************
Ran 0 test cases in 0.96s (1.38s CPU)
All 3 modules OK

```

**Comment by leonardt** [comment] 2018-05-30 17:36
@steveri I've pushed a change to the `lut-unit-test-random` branch (can check it out with `git checkout -b lut-unit-test-random` that enables the random op.

To run the lut test in particular you can use `pytest test_pe.py -k test_lut`

It took me 3 tries to get a failure. It dumps out quite a bit of failures because it runs a bunch of tests for each possible `lut_code` (this is the look up table value). To trim down the number of tests, you can change how the lut is parameterized, for example to only test a `lut_code` of 0:
```
diff --git a/tests/test_pe/test_pe.py b/tests/test_pe/test_pe.py
index b3de259..e2cf96e 100644
--- a/tests/test_pe/test_pe.py
+++ b/tests/test_pe/test_pe.py
@@ -115,7 +115,8 @@ def pytest_generate_tests(metafunc):
         metafunc.parametrize("flag_sel", range(0, 16))
     if 'lut_code' in metafunc.fixturenames:
-        metafunc.parametrize("lut_code", range(0, 16))
+        # metafunc.parametrize("lut_code", range(0, 16))
+        metafunc.parametrize("lut_code", [0])
     if 'random_op' in metafunc.fixturenames:
         metafunc.parametrize("random_op", [choice(ops)])
```

metafunc.parametrize takes an iterator of parameters for the test (we default to testing all the lut_codes from 0 to 16, this diff shows changing it to just a list of one lut value).

Here's an example failure output, you can see near the top the parameters that the test failed on `strategy = <function complete at 0x7ff4258ee2f0>, signed = False, lut_code = 0, worker_id = 'master', random_op = 'or_'`

```
____________________________________________________________ test_lut[False-complete-0-or_] _____________________________________________________________
strategy = <function complete at 0x7ff4258ee2f0>, signed = False, lut_code = 0, worker_id = 'master', random_op = 'or_'
    def test_lut(strategy, signed, lut_code, worker_id, random_op):                                                                              [0/1814]
        op = random_op
        # op = choice(ops)
        # op = "add"
        flag_sel = 0xE  # Lut output
        bit2_mode = 0x2  # BYPASS
        bit1_mode = 0x2  # BYPASS
        bit0_mode = 0x2  # BYPASS
        data1_mode = 0x2  # BYPASS
        data0_mode = 0x2  # BYPASS
        irq_en = 0
        acc_en = 0
        _op = getattr(pe, op)().flag(flag_sel).lut(lut_code).signed(signed)
        cfg_d = _op.instruction
        if strategy is complete:
            width = 4
            N = 1 << width
            tests = complete(_op, OrderedDict([
                ("data0", range(-1, 1)),  # For now we'll verify that data0/data1
                ("data1", range(-1, 1)),  # don't affect the output
                ("bit0", range(0, 2)),
                ("bit1", range(0, 2)),
                ("bit2", range(0, 2)),
            ]), lambda result: (test_output("res", result[0]),
                                test_output("res_p", result[1]),
                                test_output("irq", 1 if result[2] else 0)))
        elif strategy is random:
            return # We just test the LUT completely
        body = bodysource(tests)
        test = testsource(tests)
        build_directory = "build_{}".format(worker_id)
        if not os.path.exists(build_directory):
            os.makedirs(build_directory)
        compile_harness(f'{build_directory}/harness.cpp', test, body, lut_code, cfg_d)
>       run_verilator_test('test_pe_unq1', 'harness', 'test_pe_unq1', build_directory)
test_pe.py:272:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
verilog_file_name = 'test_pe_unq1', driver_name = 'harness', top_module = 'test_pe_unq1'
build_dir = '/horowitz/users/lenny/CGRAGenerator/tests/test_pe/build_master'
    def run_verilator_test(verilog_file_name, driver_name, top_module, build_dir="build"):
        (_, filename, _, _, _, _) = inspect.getouterframes(inspect.currentframe())[1]
        file_path = os.path.dirname(filename)
        build_dir = os.path.join(file_path, build_dir)
        if not os.path.isfile(os.path.join(build_dir, "obj_dir", f"V{top_module}.mk")):
            # print("========== BEGIN: Using verilator to generate test files =====")
            assert not subprocess.call('verilator -I../rtl -Wno-fatal --cc {} --exe {}.cpp --top-module {}'.format(verilog_file_name, driver_name, top_mo
dule), cwd=build_dir, shell=True)
            # print("========== DONE:  Using verilator to generate test files =====")
        # print("========== BEGIN: Compiling verilator test ===================")
        assert not subprocess.call('make --silent -C obj_dir -j -f V{0}.mk V{0}'.format(top_module), cwd=build_dir, shell=True)
        # print("========== DONE:  Compiling verilator test ===================")
        # print("========== BEGIN: Running verilator test =====================")
>       assert not subprocess.call('./obj_dir/V{}'.format(top_module), cwd=build_dir, shell=True)
E       AssertionError
verilator.py:122: AssertionError
----------------------------------------------------------------- Captured stdout call ------------------------------------------------------------------
[Test Iteration 0] Inputs: data0=ffff, data1=ffff, bit0=0, bit1=0, bit2=0
    expected_res=0, actual_res=ffff
----------------------------------------------------------------- Captured stderr call ------------------------------------------------------------------
Vtest_pe_unq1: ../harness.cpp:116: int main(int, char**, char**): Assertion `top->res == test[5]' failed.
================================================================= 2769 tests deselected =================================================================
================================================== 2 failed, 2 passed, 2769 deselected in 1.72 seconds =================================================
```

It looks like it's failing on the expected output of `res` (the op) which shouldn't be affected by the lut_code? In the test that failed, we're running an `or` of `0xffff` with `0xffff` so the output should be `0xffff` but we get 0.

One note is that usually we use `./CGRAGenerator/tests/test_pe/run_tests.sh` which calls `generate.csh`, so you'll want to be sure to run `generate.csh` to regenerate the verilog any time you make a change to the generator (would be great to make this better using some Make style build dependency tracker).

**Comment by steveri** [comment] 2018-06-01 17:42
@leonardt NVM looks like I made it to Level Two.  I have not yet managed to reproduce anything yet, but I think I'm getting closer anyway ... :)

```
python3.6 /usr/bin/pytest | & less
DeprecationWarning: the imp module is deprecated
DeprecationWarning: inspect.getargspec() is deprecated
DeprecationWarning: [logilab-common 1.3] logilab-pytest is deprecated, use another test runner

=======================  test_compute_unit.py  =======================

============================  test_pe.py  ============================

==========================  testvectors.py  ==========================

no test dir found testing here: /nobackup/steveri/github/CGRAGenerator/tests/test_pe
*******************************************************************************
Ran 0 test cases in 0.96s (1.38s CPU)
All 3 modules OK

```

**Comment by steveri** [comment] 2018-06-01 17:46
Okay @leonardt thanks to your help i got miniconda3 installed and pytest is running.  BUT!  I have not yet been able to replicate the problem.  I build a file "bad_lut.py" using the instructions above (i.e. same as test_lut except uses choice(ops) instead of "add") and ran it ten times in a row (csh syntax):

```
foreach i ( 0 1 2 3 4 5 6 7 8 9 )
  pytest bad_lut.py -k test_lut
end
```

...and it passed every time.  Now I am doing similar test except without the "-k" option, I expect this will take awhile.  I am running from branch "dev"

**Comment by leonardt** [comment] 2018-06-01 22:46
interesting, are you running on the dev branch? My failures were on master so maybe a change could have fixed the issue.

**Comment by steveri** [comment] 2018-06-04 17:43
Running on master now, but it's not looking good i.e. not failed yet; only partway through first test though so still could happen, I will update you in a while.  FYI my "bad_lut" that I am testing is different from "test_pe" in the following way:

```
% diff test_pe.py bad_lut.py
232a233
> import sys;
233a235
> 
235,236c237,247
<     # op = choice(ops)
<     op = "add"
---
> 
> # -    # op = choice(ops)
> # -    op = "add"
> # +    op = choice(ops)
> # +    # op = "add"
> 
>     op = choice(ops)
>     # op = "add"
>     sys.stderr.write('FOO: "%s"\n' % op)

```

**Comment by steveri** [comment] 2018-12-12 19:19
@leonardt should we close this issue out as well...seems like it's pretty stale by now...

**Comment by leonardt** [comment] 2018-12-12 21:20
Your call, I haven't had any time to investigate this. If we can't reproduce it easily, then we can close it and open a new issue if it resurfaces.

**Comment by steveri** [comment] 2018-12-12 21:59
hm i think i will try one more time (to duplicate the error) before i give up...
https://travis-ci.org/StanfordAHA/CGRAGenerator/builds/467223467

**Comment by steveri** [comment] 2018-12-13 15:51
@leonardt huh got unexpected new error(s) you might want to take a look:
https://travis-ci.org/StanfordAHA/CGRAGenerator/builds/467223467

Mostly it's this error, multiple times:
```
>       _op = getattr(pe, op)().flag(flag_sel).lut(lut_code).signed(signed)
E       TypeError: shr() missing 1 required positional argument: 'signed'
```

Probably a very easy fix and I could maybe do it if you want, but I thought I 'd let give you an opportunity to take the first crack at it...this is the only change I made vs. existing dev branch, to produce the error:

```
diff --git a/tests/test_pe/test_pe.py b/tests/test_pe/test_pe.py
index 1b2c827..b34938f 100644
--- a/tests/test_pe/test_pe.py
+++ b/tests/test_pe/test_pe.py
@@ -236,8 +236,8 @@ def test_input_modes(signed, worker_id, input_modes):
 
 def test_lut(strategy, signed, lut_code, worker_id): #, random_op):
     # op = random_op
-    # op = choice(ops)
-    op = "add"
+    op = choice(ops) # fail?
+    # op = "add"     # pass
     flag_sel = 0xE  # Lut output
     bit2_mode = 0x2  # BYPASS
     bit1_mode = 0x2  # BYPASS
```

**Comment by leonardt** [comment] 2018-12-13 19:00
Just pushed a fix, the lut test hadn't been updated for the new API for signed ops, let's see how that goes.

**Comment by leonardt** [comment] 2018-12-13 19:01
Including the new travis build to watch for reference: https://travis-ci.org/StanfordAHA/CGRAGenerator/builds/467658740

**Comment by steveri** [comment] 2018-12-13 19:34
Thanks!  Looks like it is passing its tests.  I think what I will do is rerun the travis test a couple of times (since the original problem was random) and if it passes consistently I will push your patch and close the issue.  As you said earlier, if the bug re-manifests we can reopen the issue.

**Closed** 2018-12-17 19:41 UTC
